spring:
  datasource:
    url: jdbc:mysql://localhost:3306/activiti?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: ft8441272


  activiti:
    process-definition-location-prefix: classpath*:/processes/
    ####校验流程文件，默认校验resources下的processes文件夹里的流程文件
    check-process-definitions: false